name: build-check

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
          cache: npm
      - run: make install
      - run: make build
      - run: make publish
      - run: make lint
      - run: make test
